def string_to_triplet(string):
    """converts a hexadecimal #xxxxxx string to a color triplet"""
    return (int(string[1: 3], 16), int(string[3: 5], 16), int(string[5: 7], 16))


aqua =       string_to_triplet("#00ffff")
black =      string_to_triplet("#000000")
blue =       string_to_triplet("#0000ff")
burlywood =  string_to_triplet("#deb887")
darkgray =   string_to_triplet("#a9a9a9")
darkgreen =  string_to_triplet("#006400")
darkkhaki =  string_to_triplet("#bdb76b")
dimgray =    string_to_triplet("#696969")
dodgerblue = string_to_triplet("#1e90ff")
fuchsia =    string_to_triplet("#ff00ff")
gold =       string_to_triplet("#ffd700")
gray =       string_to_triplet("#808080")
green =      string_to_triplet("#00ff00")
khaki =      string_to_triplet("#f0e68c")
lime =       string_to_triplet("#00ff00")
maroon =     string_to_triplet("#800000")
moccasin =   string_to_triplet("#ffe4b5")
navy =       string_to_triplet("#000080")
olive =      string_to_triplet("#808000")
purple =     string_to_triplet("#800080")
red =        string_to_triplet("#ff0000")
silver =     string_to_triplet("#c0c0c0")
teal =       string_to_triplet("#008080")
white =      string_to_triplet("#ffffff")
yellow =     string_to_triplet("#ffff00")